name: Single test run over devices groups

'on':
  workflow_dispatch:
    inputs:
      test:
        type: string
        description: Test to run
        default: ''
      deviceGroup:
        type: choice
        description: Group of devices
        default: ALL_BROWSERS
        options:
          - ALL_BROWSERS
          - ALL_IOS_DEVICES
          - ALL_ANDROID_DEVICES
          - ALL_PHONE_DEVICES
          - ALL_TABLET_DEVICES
      environment:
        type: choice
        description: Testing Environment
        default: DE_LIVE
        options:
          - DE_LIVE
          - DE_PRE_LIVE
          - DE_TUI
      logApiCalls:
        type: choice
        description: Log API calls
        default: true
        options:
          - true
          - false
jobs:

  BROWSERS:
    if: inputs.deviceGroup == 'ALL_BROWSERS'
    runs-on:
      - self-hosted
      - opsvpc-customer
      - small
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        ALL_BROWSERS: ['BS_Chrome.json', 'BS_Firefox.json', 'BS_Safari.json', 'BS_Edge.json']
    steps:
      - uses: actions/checkout@v3
      - uses: ApplauseAuto/gha-shared/.github/actions/mvn_java_setup@v0.0.1
      - name: maven-settings
        uses: s4u/maven-settings-action@v2
        with:
          servers: >-
            [{"id": "github", "username": "rdutu", "password":
            "${GITHUB_TOKEN_REF}"}]
          githubServer: false

      - name: Run BROWSERS
        continue-on-error: false
        env:
          GITHUB_TOKEN_REF: '${{ secrets.ARTIFACTORY_SECRET }}'
        run: |
          mvn clean compile test -DdriverConfig=${{ matrix.ALL_BROWSERS }} -DtestRailReportingEnabled=false -DaddAllTestsToPlan=false -Dtest=${{ inputs.test }} -DproductId=${{ secrets.PRODUCT_ID }} -DapiKey=${{ secrets.APPLAUSE_API_KEY }} -DttuseTunnel=true "-DrunDateStamp=2023-08-15 07:10:54 UTC" -DrunningConfiguration=${{ inputs.environment }} "-DciJobName=169-DE-LIVE-2023-08-15 07:10:54 UTC" -DlaunchName=testRunName -DlogApiCalls=${{ inputs.logApiCalls }} -DtestRailProjectId=10 -DtestRailRunName=null -DuseXray=false -DtestRailPlanName=null -Dbrowser=${{ inputs.browser }} -DtestRailSuiteId=39698 -DqualityappsApiAuthIdentifier=automation -DqualityappsApiAuthPassword=pTdprh*h.meVTmERA6 -Dexecution=clientside -DtestRailRunNameAllowReuse=true -Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts --no-transfer-progress --s Settings.xml

      - uses: ApplauseAuto/gha-shared/.github/actions/allure_reporting@v0.0.1
        with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
         allure-report: target/graph-test-report

  IOS_DEVICES:
    if: inputs.deviceGroup == 'ALL_IOS_DEVICES'
    runs-on:
      - self-hosted
      - opsvpc-customer
      - small
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        ALL_IOS_DEVICES: ['BS_iOS_Phone.json', 'BS_iOS_Tablet.json']
    steps:
      - uses: actions/checkout@v3
      - uses: ApplauseAuto/gha-shared/.github/actions/mvn_java_setup@v0.0.1
      - name: maven-settings
        uses: s4u/maven-settings-action@v2
        with:
          servers: >-
            [{"id": "github", "username": "rdutu", "password":
            "${GITHUB_TOKEN_REF}"}]
          githubServer: false

      - name: Run IOS_DEVICES
        continue-on-error: false
        env:
          GITHUB_TOKEN_REF: '${{ secrets.ARTIFACTORY_SECRET }}'
        run: |
          mvn clean compile test -DdriverConfig=${{ matrix.ALL_IOS_DEVICES }} -DtestRailReportingEnabled=false -DaddAllTestsToPlan=false -Dtest=${{ inputs.test }} -DproductId=${{ secrets.PRODUCT_ID }} -DapiKey=${{ secrets.APPLAUSE_API_KEY }} -DttuseTunnel=true "-DrunDateStamp=2023-08-15 07:10:54 UTC" -DrunningConfiguration=${{ inputs.environment }} "-DciJobName=169-DE-LIVE-2023-08-15 07:10:54 UTC" -DlaunchName=testRunName -DlogApiCalls=${{ inputs.logApiCalls }} -DtestRailProjectId=10 -DtestRailRunName=null -DuseXray=false -DtestRailPlanName=null -Dbrowser=${{ inputs.browser }} -DtestRailSuiteId=39698 -DqualityappsApiAuthIdentifier=automation -DqualityappsApiAuthPassword=pTdprh*h.meVTmERA6 -Dexecution=clientside -DtestRailRunNameAllowReuse=true -Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts --no-transfer-progress

      - uses: ApplauseAuto/gha-shared/.github/actions/allure_reporting@v0.0.1
        with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
         allure-report: target/graph-test-report

  ANDROID_DEVICES:
    if: inputs.deviceGroup == 'ALL_ANDROID_DEVICES'
    runs-on:
      - self-hosted
      - opsvpc-customer
      - small
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        ALL_ANDROID_DEVICES: ['BS_Android_Phone.json', 'BS_Android_Tablet.json']
    steps:
      - uses: actions/checkout@v3
      - uses: ApplauseAuto/gha-shared/.github/actions/mvn_java_setup@v0.0.1
      - name: maven-settings
        uses: s4u/maven-settings-action@v2
        with:
          servers: >-
            [{"id": "github", "username": "rdutu", "password":
            "${GITHUB_TOKEN_REF}"}]
          githubServer: false

      - name: Run ANDROID_DEVICES
        continue-on-error: false
        env:
          GITHUB_TOKEN_REF: '${{ secrets.ARTIFACTORY_SECRET }}'
        run: |
          mvn clean compile test -DdriverConfig=${{ matrix.ALL_ANDROID_DEVICES }} -DtestRailReportingEnabled=false -DaddAllTestsToPlan=false -Dtest=${{ inputs.test }} -DproductId=${{ secrets.PRODUCT_ID }} -DapiKey=${{ secrets.APPLAUSE_API_KEY }} -DttuseTunnel=true "-DrunDateStamp=2023-08-15 07:10:54 UTC" -DrunningConfiguration=${{ inputs.environment }} "-DciJobName=169-DE-LIVE-2023-08-15 07:10:54 UTC" -DlaunchName=testRunName -DlogApiCalls=${{ inputs.logApiCalls }} -DtestRailProjectId=10 -DtestRailRunName=null -DuseXray=false -DtestRailPlanName=null -Dbrowser=${{ inputs.browser }} -DtestRailSuiteId=39698 -DqualityappsApiAuthIdentifier=automation -DqualityappsApiAuthPassword=pTdprh*h.meVTmERA6 -Dexecution=clientside -DtestRailRunNameAllowReuse=true -Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts --no-transfer-progress

      - uses: ApplauseAuto/gha-shared/.github/actions/allure_reporting@v0.0.1
        with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
         allure-report: target/graph-test-report

  PHONE_DEVICES:
    if: inputs.deviceGroup == 'ALL_PHONE_DEVICES'
    runs-on:
      - self-hosted
      - opsvpc-customer
      - small
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        ALL_PHONE_DEVICES: ['BS_Android_Phone.json', 'BS_iOS_Phone.json']
    steps:
      - uses: actions/checkout@v3
      - uses: ApplauseAuto/gha-shared/.github/actions/mvn_java_setup@v0.0.1
      - name: maven-settings
        uses: s4u/maven-settings-action@v2
        with:
          servers: >-
            [{"id": "github", "username": "rdutu", "password":
            "${GITHUB_TOKEN_REF}"}]
          githubServer: false

      - name: Run PHONE_DEVICES
        continue-on-error: false
        env:
          GITHUB_TOKEN_REF: '${{ secrets.ARTIFACTORY_SECRET }}'
        run: |
          mvn clean compile test -DdriverConfig=${{ matrix.ALL_PHONE_DEVICES }} -DtestRailReportingEnabled=false -DaddAllTestsToPlan=false -Dtest=${{ inputs.test }} -DproductId=${{ secrets.PRODUCT_ID }} -DapiKey=${{ secrets.APPLAUSE_API_KEY }} -DttuseTunnel=true "-DrunDateStamp=2023-08-15 07:10:54 UTC" -DrunningConfiguration=${{ inputs.environment }} "-DciJobName=169-DE-LIVE-2023-08-15 07:10:54 UTC" -DlaunchName=testRunName -DlogApiCalls=${{ inputs.logApiCalls }} -DtestRailProjectId=10 -DtestRailRunName=null -DuseXray=false -DtestRailPlanName=null -Dbrowser=${{ inputs.browser }} -DtestRailSuiteId=39698 -DqualityappsApiAuthIdentifier=automation -DqualityappsApiAuthPassword=pTdprh*h.meVTmERA6 -Dexecution=clientside -DtestRailRunNameAllowReuse=true -Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts --no-transfer-progress

      - uses: ApplauseAuto/gha-shared/.github/actions/allure_reporting@v0.0.1
        with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
         allure-report: target/graph-test-report

  TABLET_DEVICES:
    if: inputs.deviceGroup == 'ALL_TABLET_DEVICES'
    runs-on:
      - self-hosted
      - opsvpc-customer
      - small
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        ALL_TABLET_DEVICES: ['BS_Android_Tablet.json', 'BS_iOS_Tablet.json']
    steps:
      - uses: actions/checkout@v3
      - uses: ApplauseAuto/gha-shared/.github/actions/mvn_java_setup@v0.0.1
      - name: maven-settings
        uses: s4u/maven-settings-action@v2
        with:
          servers: >-
            [{"id": "github", "username": "rdutu", "password":
            "${GITHUB_TOKEN_REF}"}]
          githubServer: false

      - name: Run TABLET_DEVICES
        continue-on-error: false
        env:
          GITHUB_TOKEN_REF: '${{ secrets.ARTIFACTORY_SECRET }}'
        run: |
          mvn clean compile test -DdriverConfig=${{ matrix.ALL_TABLET_DEVICES }} -DtestRailReportingEnabled=false -DaddAllTestsToPlan=false -Dtest=${{ inputs.test }} -DproductId=${{ secrets.PRODUCT_ID }} -DapiKey=${{ secrets.APPLAUSE_API_KEY }} -DttuseTunnel=true "-DrunDateStamp=2023-08-15 07:10:54 UTC" -DrunningConfiguration=${{ inputs.environment }} "-DciJobName=169-DE-LIVE-2023-08-15 07:10:54 UTC" -DlaunchName=testRunName -DlogApiCalls=${{ inputs.logApiCalls }} -DtestRailProjectId=10 -DtestRailRunName=null -DuseXray=false -DtestRailPlanName=null -Dbrowser=${{ inputs.browser }} -DtestRailSuiteId=39698 -DqualityappsApiAuthIdentifier=automation -DqualityappsApiAuthPassword=pTdprh*h.meVTmERA6 -Dexecution=clientside -DtestRailRunNameAllowReuse=true -Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts --no-transfer-progress

      - uses: ApplauseAuto/gha-shared/.github/actions/allure_reporting@v0.0.1
        with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
         allure-report: target/graph-test-report