name: Single test run

'on':
  workflow_dispatch:
    inputs:
      test:
        type: string
        description: Test to run
        default: ''
      browser:
        type: choice
        description: Browser Type
        default: BS_Chrome.json
        options:
          - BS_Chrome.json
          - BS_Firefox.json
          - BS_Safari.json
          - BS_Edge.json
          - BS_Android_Phone.json
          - BS_Android_Tablet.json
          - BS_iOS_Phone.json
          - BS_iOS_Tablet.json
      environment:
        type: choice
        description: Testing Environment
        default: LIVE
        options:
          - LIVE
          - PRE_LIVE
      locale:
        type: choice
        description: Select running locale
        default: US
        options:
          - US
          - UK
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: maven-settings
        uses: s4u/maven-settings-action@v2
        with:
          servers: >-
            [{"id": "github", "username": "rdutu", "password":
            "${GITHUB_TOKEN_REF}"}]
          githubServer: false
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Prepare running variables
        run: echo "RUNNING_DATE=$(date +'%d/%m/%Y')" >> $GITHUB_ENV

      - name: Run Test
        continue-on-error: false
        env:
          GITHUB_TOKEN_REF: '${{ secrets.ARTIFACTORY_SECRET }}'
        run: mvn clean compile test -DdriverConfig=${{ inputs.browser }} -DtestRailReportingEnabled=false -DaddAllTestsToPlan=false -Dtest=${{ inputs.test }} -DproductId=33483 -DapiKey=${{ secrets.APPLAUSE_API_KEY }} "-DrunDateStamp=2023-08-15 07:10:54 UTC" -DrunningConfiguration=${{ inputs.environment }} "-DciJobName=169-DE-LIVE-2023-08-15 07:10:54 UTC" -DtestRailProjectId=109 -Dbrowser=${{ inputs.browser }} -DtestRailSuiteId=50375 -Dexecution=clientside -DtestRailRunNameAllowReuse=true -DuseLocalDrivers=false -Dlocale=${{ inputs.locale }} -Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts --no-transfer-progress --s Settings.xml